In [1]:
import gymnasium as gym
import minigrid
from minigrid.envs import GoToObjectEnv
import pygame
import numpy as np
import torch
import os

In [2]:
env = GoToObjectEnv(
    size=20, 
    max_steps=200, 
    render_mode="human",
    agent_view_size=3,
    # see_through_walls=False,
)

In [3]:
os.environ['SDL_VIDEO_WINDOW_POS'] = '6500,0'

In [4]:
obs, _ = env.reset()
print(obs['image'])
print(obs['direction'])
print(obs['mission'])

[[[1 0 0]
  [1 0 0]
  [1 0 0]]

 [[1 0 0]
  [1 0 0]
  [1 0 0]]

 [[1 0 0]
  [1 0 0]
  [1 0 0]]]
1
go to the grey key


In [5]:
# pygame.init()
# window_size = (env.render().shape[1], env.render().shape[0])  # Get size from the env frame
# screen = pygame.display.set_mode(window_size)
# pygame.display.set_caption("Minigrid Environment")

In [6]:
# import random

# for _ in range(20):  # Take 20 random actions
#     # while action:= int(input("What action should the agent take: ")) not in []:
#     action = random.randint(0, 2)
#     # action = env.action_space.sample()  # Sample a random action
#     obs, reward, terminated, truncated, info = env.step(action)  # Take the action
#     frame = env.render()
#     frame_surface = pygame.surfarray.make_surface(np.transpose(frame, (1,0,2)))
#     screen.blit(frame_surface, (0,0))
#     pygame.display.flip()
    
#     # print("Action:", action)
#     # print("Observation:", obs)
#     # print("Reward:", reward)
#     # print("Terminated:", terminated)

#     if terminated or truncated:
#         obs = env.reset()  # Reset if the episode is over

In [7]:
# env.close()
# pygame.quit()

In [8]:
from agent import Agent

In [9]:
agent = Agent(
    input_space_size=20,
    output_space_size=7,
    lstm_hidden_size=128, 
    lstm_num_layers=2,
)

tensor([0., 0., 0., -inf, -inf, -inf, 0.])


In [10]:
dummy_data = np.random.rand(3, 2, 2, 5)
dummy_data.shape

(3, 2, 2, 5)

In [11]:
t = torch.tensor(dummy_data, dtype=torch.float32).flatten(1)
t.size()

torch.Size([3, 20])

In [ ]:
agent.train(dummy_data)

(tensor([-0.0290, -0.0308, -0.0313], device='cuda:0', grad_fn=<SelectBackward0>),
 tensor([[0.2302, 0.2328, 0.2673, 0.0000, 0.0000, 0.0000, 0.2697],
         [0.2302, 0.2325, 0.2676, 0.0000, 0.0000, 0.0000, 0.2697],
         [0.2297, 0.2328, 0.2675, 0.0000, 0.0000, 0.0000, 0.2699]],
        device='cuda:0', grad_fn=<SoftmaxBackward0>))

: 